# -*- coding: utf-8 -*-
"""Final_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T3_UnC19AvAibgPpguWvx3o8Mo7kUDDz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("COVID_Parcel_Business.csv")
df.head()

print(df.shape)
print(df.columns)
print(df.info())
print(df.describe())
print(df.isna().sum())

df.columns = ["CustomerID", "Year", "Week", "Volume"]
df.head()

yearly = df.groupby("Year")["Volume"].sum().reset_index()
yearly

yearly = df.groupby("Year")["Volume"].sum().reset_index()
yearly

plt.figure(figsize=(8,5))
plt.bar(yearly["Year"].astype(str), yearly["Volume"])
plt.title("Total Parcel Volume by Year")
plt.xlabel("Year")
plt.ylabel("Total Parcels")
plt.show()

weekly = df.groupby(["Year", "Week"], as_index=False)["Volume"].sum()

plt.figure(figsize=(12,6))
for yr in [2019, 2020]:
    temp = weekly[weekly["Year"] == yr]
    plt.plot(temp["Week"], temp["Volume"], marker='o', label=str(yr))

plt.title("Weekly Parcel Volume: 2019 vs 2020")
plt.xlabel("Week")
plt.ylabel("Total Parcels")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

pre_2019 = df[(df["Year"] == 2019) & (df["Week"].between(1,15))]["Volume"].sum()
pre_2020 = df[(df["Year"] == 2020) & (df["Week"].between(1,15))]["Volume"].sum()

isgr = (pre_2020 - pre_2019) / pre_2019

print("Pre-COVID 2019:", pre_2019)
print("Pre-COVID 2020:", pre_2020)
print("ISGR:", isgr)
print("ISGR %:", round(isgr*100, 2), "%")

covid_2019 = df[(df["Year"] == 2019) & (df["Week"].between(16,53))]["Volume"].sum()
covid_2020 = df[(df["Year"] == 2020) & (df["Week"].between(16,53))]["Volume"].sum()

covid_growth = (covid_2020 - covid_2019) / covid_2019

print("2019 baseline for COVID period:", covid_2019)
print("2020 COVID period:", covid_2020)
print("COVID period growth %:", round(covid_growth*100, 2))

pivot = weekly.pivot(index="Week", columns="Year", values="Volume")
pivot["Diff"] = pivot[2020] - pivot[2019]
pivot["Pct_Diff"] = pivot["Diff"] / pivot[2019]

pivot.loc[1:20]

peak_2019_20 = df[((df["Year"] == 2019) & (df["Week"] >= 45)) | ((df["Year"] == 2020) & (df["Week"] <= 3))]["Volume"].sum()
peak_2020_21 = df[((df["Year"] == 2020) & (df["Week"] >= 45)) | ((df["Year"] == 2021) & (df["Week"] <= 3))]["Volume"].sum()

peak_growth = (peak_2020_21 - peak_2019_20) / peak_2019_20

print("Peak 2019-20:", peak_2019_20)
print("Peak 2020-21:", peak_2020_21)
print("Peak growth %:", round(peak_growth*100, 2))

customers = pd.DataFrame({"CustomerID": sorted(df["CustomerID"].unique())}).set_index("CustomerID")

customers["vol_2019_all"] = df[df["Year"] == 2019].groupby("CustomerID")["Volume"].sum()
customers["vol_pre2020"] = df[(df["Year"] == 2020) & (df["Week"].between(1,15))].groupby("CustomerID")["Volume"].sum()
customers["vol_covid2019_base"] = df[(df["Year"] == 2019) & (df["Week"].between(16,53))].groupby("CustomerID")["Volume"].sum()
customers["vol_covid2020"] = df[(df["Year"] == 2020) & (df["Week"].between(16,53))].groupby("CustomerID")["Volume"].sum()

customers = customers.fillna(0)

isgr = (pre_2020 - pre_2019) / pre_2019

customers["new_customer"] = ((customers["vol_2019_all"] + customers["vol_pre2020"]) == 0) & (customers["vol_covid2020"] > 0)
customers["lost_customer"] = ((customers["vol_2019_all"] + customers["vol_pre2020"]) > 0) & (customers["vol_covid2020"] == 0)

customers["growth_rate_covid"] = np.where(
    customers["vol_covid2019_base"] > 0,
    (customers["vol_covid2020"] - customers["vol_covid2019_base"]) / customers["vol_covid2019_base"],
    np.nan
)

conditions = [
    customers["new_customer"],
    customers["lost_customer"],
    (~customers["new_customer"]) & (~customers["lost_customer"]) & (customers["growth_rate_covid"] < 0),
    (~customers["new_customer"]) & (~customers["lost_customer"]) & (customers["growth_rate_covid"] >= 0) & (customers["growth_rate_covid"] <= isgr),
    (~customers["new_customer"]) & (~customers["lost_customer"]) & (customers["growth_rate_covid"] > isgr)
]

choices = ["New", "Lost", "Declining", "Stable", "High Growth"]

customers["status"] = np.select(conditions, choices, default="Unclassified")

customers["status"].value_counts()

status_counts = customers["status"].value_counts()

plt.figure(figsize=(7,7))
plt.pie(status_counts, labels=status_counts.index, autopct='%1.1f%%', startangle=90)
plt.title("Customer Status During COVID Period")
plt.show()

customers["vol2019"] = customers["vol_2019_all"]

q50 = customers["vol2019"].quantile(0.50)
q75 = customers["vol2019"].quantile(0.75)
q95 = customers["vol2019"].quantile(0.95)

def assign_group(v):
    if v >= q95:
        return "Enterprise"
    elif v >= q75:
        return "Large"
    elif v >= q50:
        return "Medium"
    else:
        return "Small"

customers["customer_group"] = customers["vol2019"].apply(assign_group)
customers["customer_group"].value_counts()

customers["vol2020"] = df[df["Year"] == 2020].groupby("CustomerID")["Volume"].sum()
customers["vol2020"] = customers["vol2020"].fillna(0)

customers["gross_rev_2019"] = customers["vol2019"] * 22
customers["gross_rev_2020"] = customers["vol2020"] * 22

group_summary = customers.groupby("customer_group").agg(
    customers=("customer_group", "size"),
    vol_2019=("vol2019", "sum"),
    vol_2020=("vol2020", "sum"),
    rev_2019=("gross_rev_2019", "sum"),
    rev_2020=("gross_rev_2020", "sum")
).reset_index()

group_summary["vol_growth_pct"] = (group_summary["vol_2020"] - group_summary["vol_2019"]) / group_summary["vol_2019"]
group_summary["rev_growth_pct"] = (group_summary["rev_2020"] - group_summary["rev_2019"]) / group_summary["rev_2019"]

group_summary

counts = customers.groupby(["customer_group", "status"]).size().unstack(fill_value=0)
status_pct = counts.div(counts.sum(axis=1), axis=0) * 100

print(status_pct.round(1))

plt.figure(figsize=(8,5))
plt.bar(group_summary["customer_group"], group_summary["vol_growth_pct"] * 100)
plt.title("Volume Growth by Customer Group (2020 vs 2019)")
plt.xlabel("Customer Group")
plt.ylabel("Growth %")
plt.show()